name: Maintenance
main: com.github.arsenalfcgunners.maintenance.Maintenance
description: Allows a server to be put into maintenance mode, a mode where only devs and higher ranks can join the server.
author: arsenalfcgunners
version: 1.0

commands:
   maintenance:
      description: Shows players our server website.
      usage: /<command>
      aliases: [dev, devmode]
      
permissions:
  gapple.dev:
    description: Allows the player to toggle maintenance mode.
